#include "dll.h"
#include "sys/main.h"
#include "sys/menu.h"

typedef enum {
    LEVELSELECT_IDX_00_NEW_GAME,
    LEVELSELECT_IDX_01_LOAD_GAME,
    LEVELSELECT_IDX_02,
    LEVELSELECT_IDX_03_SWAPSTONE_HOLLOW,
    LEVELSELECT_IDX_04_SWAPSTONE_CIRCLE,
    LEVELSELECT_IDX_05,
    LEVELSELECT_IDX_06_DARKICE_MINES,
    LEVELSELECT_IDX_07_DARKICE_MINES_TWO,
    LEVELSELECT_IDX_08_WALLED_CITY,
    LEVELSELECT_IDX_09_DRAGON_ROCK,
    LEVELSELECT_IDX_0A_CLOUDRUNNER_FORTRESS,
    LEVELSELECT_IDX_0B_KRAZOA_PALACE,
    LEVELSELECT_IDX_0C_BLACKWATER_CANYON,
    LEVELSELECT_IDX_0D,
    LEVELSELECT_IDX_0E_NORTHERN_WASTES,
    LEVELSELECT_IDX_0F_EARTHWALKER_TEMPLE,
    LEVELSELECT_IDX_10_WILLOW_GROVE,
    LEVELSELECT_IDX_11_DIAMOND_BAY,
    LEVELSELECT_IDX_12_DISCOVERY_FALLS,
    LEVELSELECT_IDX_13_MOON_MOUNTAIN_PASS,
    LEVELSELECT_IDX_14_CAPE_CLAW,
    LEVELSELECT_IDX_15_GOLDEN_PLAINS,
    LEVELSELECT_IDX_16,
    LEVELSELECT_IDX_17_TEST_OF_COMBAT,
    LEVELSELECT_IDX_18_TEST_OF_STRENGTH,
    LEVELSELECT_IDX_19_TEST_OF_FEAR,
    LEVELSELECT_IDX_1A_TEST_OF_CHARACTER,
    LEVELSELECT_IDX_1B_TEST_OF_KNOWLEDGE,
    LEVELSELECT_IDX_1C_TEST_OF_SACRIFICE,
    LEVELSELECT_IDX_1D_TEST_OF_SKILL,
    LEVELSELECT_IDX_1E_TEST_OF_MAGIC,
    LEVELSELECT_IDX_1F,
    LEVELSELECT_IDX_20,
    LEVELSELECT_IDX_21_DARKICE_BOSS,
    LEVELSELECT_IDX_22_GENERAL_SCALES_BOSS,
    LEVELSELECT_IDX_23_BLACKWATER_BOSS,
    LEVELSELECT_IDX_24_CLOUDRUNNER_RACE,
    LEVELSELECT_IDX_25_KAMERIA_DRAGON_BOSS,
    LEVELSELECT_IDX_26_DRAKOR_FINAL_BOSS,
    LEVELSELECT_IDX_27_ICE_MOUNTAIN,
    LEVELSELECT_IDX_28,
    LEVELSELECT_IDX_29_DESERT_FORCE_POINT,
    LEVELSELECT_IDX_2A_VOLCANO_FORCE_POINT,
    LEVELSELECT_IDX_2B,
    LEVELSELECT_IDX_2C_EARTHWALKER_ACT_TWO, 
    LEVELSELECT_IDX_2D_ENERGY_DEMO,
    LEVELSELECT_IDX_2E, 
    LEVELSELECT_IDX_2F_WARLOCK_ACT_ONE,
    LEVELSELECT_IDX_30_WARLOCK_ACT_TWO,
    LEVELSELECT_IDX_31_WARLOCK_ACT_THREE,
    LEVELSELECT_IDX_32_WARLOCK_ACT_FOUR,
    LEVELSELECT_IDX_33_WARLOCK_ACT_FIVE,
    LEVELSELECT_IDX_34_WARLOCK_ACT_SIX
} LevelSelectOld_Indices;

/*0x0*/ static char data_0[][64] = {
    "NEW GAME",
    "LOAD GAME",
    "",
    "SWAPSTONE HOLLOW",
    "SWAPSTONE CIRCLE",
    "",
    "DARKICE MINES",
    "DARKICE MINES TWO",
    "WALLED CITY",
    "DRAGON ROCK",
    "CLOUDRUNNER FORTRESS",
    "KRAZOA PALACE",
    "BLACKWATER CANYON",
    "",
    "NORTHERN WASTES",
    "EARTHWALKER TEMPLE",
    "WILLOW GROVE",
    "DIAMOND BAY",
    "DISCOVERY FALLS",
    "MOON MOUNTAIN PASS",
    "CAPE CLAW",
    "GOLDEN PLAINS",
    "",
    "TEST OF COMBAT",
    "TEST OF STRENGTH",
    "TEST OF FEAR",
    "TEST OF CHARACTER",
    "TEST OF KNOWLEDGE",
    "TEST OF SACRIFICE",
    "TEST OF SKILL",
    "TEST OF MAGIC",
    "",
    "",
    "DARKICE BOSS",
    "GENERAL SCALES BOSS",
    "BLACKWATER BOSS",
    "CLOUDRUNNER RACE",
    "KAMERIA DRAGON BOSS",
    "DRAKOR FINAL BOSS",
    "ICE MOUNTAIN",
    "",
    "DESERT FORCE POINT",
    "VOLCANO FORCE POINT",
    ""
};
/*0xB00*/ static char data_B00[][64] = {
    "EARTHWALKER ACT TWO", 
    "ENERGY DEMO",
    "", 
    "WARLOCK ACT ONE",
    "WARLOCK ACT TWO",
    "WARLOCK ACT THREE",
    "WARLOCK ACT FOUR",
    "WARLOCK ACT FIVE",
    "WARLOCK ACT SIX"
};
/*0xD40*/ static u32 data_D40 = 0x00000000;
/*0xD44*/ static u32 data_D44 = 0x00000000;
/*0xD48*/ static u32 data_D48[] = {
    0x00000000, 0x00000000
};

/*0x0*/ static u8 bss_0[0x10];

// offset: 0x0 | ctor
void dll_70_ctor(void *dll) { }

// offset: 0xC | dtor
void dll_70_dtor(void *dll) { }

// offset: 0x18 | func: 0 | export: 0
s32 dll_70_func_18(void) {
    return 0;
}

// offset: 0x24 | func: 1 | export: 1
void dll_70_func_24(void) {

}

// offset: 0x2C | func: 2 | export: 2
#pragma GLOBAL_ASM("asm/nonmatchings/dlls/engine/70/dll_70_func_2C.s")

// offset: 0xB58 | func: 3
void dll_70_func_B58(s32 mapID, s32 act, s32 playerNo) {
    gDLL_5_AMSEQ2->vtbl->set(NULL, 0x23, 0, 0, 0);
    gDLL_29_Gplay->vtbl->init_save(0, NULL);
    main_change_map(mapID, act, playerNo, MENU_GAMEPLAY);
}
