#ifndef _GAME_GAMETEXTS_H
#define _GAME_GAMETEXTS_H

typedef enum {
        GAMETEXT_000_Pause_Menu = 0x0, //CONTINUE
        GAMETEXT_001_Krazoa_Translator = 0x1, //THE GREAT BATTLE
        GAMETEXT_002_SW_FrostWeed_feast = 0x2, //Chomp Chomp Hmmm.... That tastes great. Hurry up boy you're a bit slow aren't you
        GAMETEXT_003_UI_Text_1 = 0x3, //HEEL
        GAMETEXT_004_Debug_Gametext_Tutorial = 0x4, //Special characters:
        GAMETEXT_005_Title_Menu = 0x5, //PRESS START
        GAMETEXT_006_SB_Krystal_intro = 0x6, //I've had a garbled message from the wizard.
        GAMETEXT_007_SB_CloudRunner_battle_tips_1 = 0x7, //Krystal!  Try shooting the cannon!
        GAMETEXT_008_SW_Garunda_Te_under_ice = 0x8, //If you bring me 12 Frost Weeds I'll be able to get myself out.
        GAMETEXT_009_CRF_Arrival = 0x9, //I'm home, Krystal
        GAMETEXT_00A_SW_Calling_for_help = 0xA, //Will somebody get me out of here!
        GAMETEXT_00B_SB_Kyte_calling_for_help_duplicate = 0xB, //Somebody get me out of Here!
        GAMETEXT_00C_SW_Tricky_Find_Command_hint = 0xC, //Use your find command to did through the snow
        GAMETEXT_00D_Debug_CloudRunner_Baby = 0xD, //THIRD BABY
        GAMETEXT_00E_Debug_Subtitle_Colours = 0xE, //r3g3b3r3g3b2
        GAMETEXT_00F_Debug_Character_Map = 0xF, //!"#$%&'()*+,-./0123456789
        GAMETEXT_010_CRF_Queen_murdered_by_Scales_1 = 0x10, //This is your last chance Queen, where is the SpellStone?
        GAMETEXT_011_CRF_Queen_murdered_by_Scales_2 = 0x11, //We've got to help her!
        GAMETEXT_012_CRF_Queen_murdered_by_Scales_3 = 0x12, //I assure you Queen, when I have all of the SpellStones, Dinosaur Planet will be mine!
        GAMETEXT_013_CRF_Queen_murdered_by_Scales_4 = 0x13, //Noooo!!
        GAMETEXT_014_CRF_Queen_murdered_by_Scales_5 = 0x14, //She's dead... she's... dead!
        GAMETEXT_015_CRF_Kyte_freed_1 = 0x15, //Did you find the Guardian yet?
        GAMETEXT_016_CRF_Kyte_freed_2 = 0x16, //To help us, I've learnt a new skill.
        GAMETEXT_017_CC_Kyte_overcomes_fears_1 = 0x17, //I'm scared of heights,
        GAMETEXT_018_CC_Kyte_overcomes_fears_2 = 0x18, //If you can go this high, then so can I.
        GAMETEXT_019_CRF_Krystal_and_Kyte_spy_on_Scales_1 = 0x19, //Guard!
        GAMETEXT_01A_CRF_Krystal_and_Kyte_spy_on_Scales_2 = 0x1A, //He was going to kill me!
        GAMETEXT_01B_SwapStone_Chat_1 = 0x1B, //Greetings Sabre.
        GAMETEXT_01C_SwapStone_Hints_1 = 0x1C, //Do you need a clue?
        GAMETEXT_01D_SwapStone_Chat_2 = 0x1D, //Are you ready to swap to Krystal?
        GAMETEXT_01E_SwapStone_Chat_3 = 0x1E, //Are you ready to warp to Warlock Mountain?
        GAMETEXT_01F_SwapStone_Hints_2 = 0x1F, //To share my knowledge you must give me two units of Magic Energy.
        GAMETEXT_020_SwapStone_Hints_3 = 0x20, //Sorry. But you do not have enough Magic Energy.
        GAMETEXT_021_SwapStone_Hints_4 = 0x21, //I hope you know what you are doing.
        GAMETEXT_022_SwapStone_Hints_5 = 0x22, //I hope this will help you.
        GAMETEXT_023_SwapStone_Chat_4 = 0x23, //Aaah, you're carrying a SpellStone.
        GAMETEXT_024_SwapStone_Chat_5 = 0x24, //You cannot swap when holding a SpellStone or carrying a Spirit!
        GAMETEXT_025_SwapStone_Chat_6 = 0x25, //You cannot swap until the stone is placed.
        GAMETEXT_026_SwapStone_Chat_7 = 0x26, //You cannot swap until the Spirit has been taken to Warlock Mountain.
        GAMETEXT_027_SwapStone_Chat_8 = 0x27, //Go to the Force Point Temple.
        GAMETEXT_028_SwapStone_Chat_9 = 0x28, //Are you ready to swap?
        GAMETEXT_029_SwapStone_Chat_10 = 0x29, //Not ready yet? Come back later.
        GAMETEXT_02A_SwapStone_Chat_11 = 0x2A, //You cannot go to Warlock Mountain until you are carrying a Spirit!
        GAMETEXT_02B_SwapStone_Chat_12 = 0x2B, //Are you ready to Warp?
        GAMETEXT_02C_SwapStone_Chat_13 = 0x2C, //Goodbye Sabre... Good luck.
        GAMETEXT_02D_SwapStone_Chat_14 = 0x2D, //Fairwell Sabre... I'll see you soon.
        GAMETEXT_02E_SW_Garunda_Te_chat_before_DIM_2 = 0x2E, //Cross the river and enter DIM
        GAMETEXT_02F_CRF_Leaving_CRF_1 = 0x2F, //When all this is over
        GAMETEXT_030_CRF_Leaving_CRF_2 = 0x30, //Scales is not going to get away with this!
        GAMETEXT_031_CRF_Krystal_confronts_Scales = 0x31, //What's going on?
        GAMETEXT_032_CRF_Krystal_gets_on_Jet_Bike = 0x32, //You`ll have to catch them and get the Spellstone
        GAMETEXT_033_CRF_Encountering_robots = 0x33, //What are those flying things?
        GAMETEXT_034_Kyte_tips_1 = 0x34, //I can burn this
        GAMETEXT_035_Kyte_tips_2 = 0x35, //You can blow this up
        GAMETEXT_036_IM_Sabre_rescues_Tricky_1 = 0x36, //Shut Up.
        GAMETEXT_037_IM_Sabre_rescues_Tricky_2 = 0x37, //Hey scaleface, pick on someone your own size!
        GAMETEXT_038_IM_Sabre_rescues_Tricky_3 = 0x38, //I am Fox Mcloud, Royal Knight of the Lylat System. I've come to take the Prince back to his ... home?
        GAMETEXT_039_WM_Skeetlas_attack_Krystal = 0x39, //Randorn are you there?
        GAMETEXT_03A_WM_Krystal_and_Randorn_discuss_Sabre = 0x3A, //Krystal,How is my son?
        GAMETEXT_03B_WM_Krystal_returns_from_DF = 0x3B, //Aaah Krystal my dear.
        GAMETEXT_03C_IM_Sabre_intro = 0x3C, //I sure hope Randorn's right about this place.
        GAMETEXT_03D_IM_Jet_Bike_challenges_1 = 0x3D, //So the wolf thinks he's fast.
        GAMETEXT_03E_IM_Jet_Bike_challenges_2 = 0x3E, //Rules are simply... first to bottom... wins.
        GAMETEXT_03F_IM_Jet_Bike_challenges_3 = 0x3F, //Wolf too scared to race?
        GAMETEXT_040_IM_Jet_Bike_challenges_4 = 0x40, //You were lucky that time.
        GAMETEXT_041_IM_Jet_Bike_challenges_5 = 0x41, //You're too slow wolf boy.
        GAMETEXT_042_IM_Jet_Bike_challenges_6 = 0x42, //We race again.
        GAMETEXT_043_IM_Jet_Bike_challenges_7 = 0x43, //Wolf too fast.
        GAMETEXT_044_WM_Disguised_Sabre_brings_Tricky_to_GuardClaw = 0x44, //Well done soldier,
        GAMETEXT_045_WM_Sabre_calling_Randorn_1 = 0x45, //Father!
        GAMETEXT_046_WM_Sabre_calling_Randorn_2 = 0x46, //Can you hear me?
        GAMETEXT_047_WM_Krystal_and_Randorn_discuss_Communication_Chamber = 0x47, //Do you remember how we got here?
        GAMETEXT_048_CC_GuardClaw_Chat_1 = 0x48, //Nobody enter Cape Claw
        GAMETEXT_049_CC_GuardClaw_Chat_2 = 0x49, //Me like Shiney things,
        GAMETEXT_04A_CC_GuardClaw_Chat_3 = 0x4A, //I'll sell you a map for ten Scarabs.
        GAMETEXT_04B_CC_GuardClaw_Chat_4 = 0x4B, //You pass,
        GAMETEXT_04C_DB_Meeting_the_PointBack_1 = 0x4C, //Leave our beach, enough of my eggs have been stolen already.
        GAMETEXT_04D_DB_PointBack_peril_3 = 0x4D, //We'll begin right away!
        GAMETEXT_04E_DB_PointBack_eggs_rescue_1 = 0x4E, //Thank you but there are still two more.
        GAMETEXT_04F_DB_PointBack_eggs_rescue_2 = 0x4F, //Just one more. Please hurry.
        GAMETEXT_050_DB_PointBack_eggs_saved_2 = 0x50, //Thanks to you my tribe shall live on. You must take this.
        GAMETEXT_051_DB_PointBack_eggs_saved_3 = 0x51, //When you are carrying a SpellStone, the map will reveal the location of a magic diamond.
        GAMETEXT_052_DB_PointBack_eggs_saved_4 = 0x52, //Collect this diamond, then place it within a hidden chamber, only then will the route to the Volcano Force Point be revealed.
        GAMETEXT_053_DB_PointBack_eggs_saved_5 = 0x53, //The map must like you, it has revealed a Krazoa Shrine.
        GAMETEXT_054_DB_PointBack_eggs_saved_6 = 0x54, //Thank you. We'd better be going now. Say goodbye Tricky.
        GAMETEXT_055_WM_Randorn_weakening = 0x55, //There is not much magic left in this mountain.
        GAMETEXT_056_CC_Krystal_rescues_LightFoot_1 = 0x56, //Are you ... Ok?
        GAMETEXT_057_CC_Krystal_rescues_LightFoot_2 = 0x57, //What sort of dinosaur are you?
        GAMETEXT_058_CC_Krystal_rescues_LightFoot_3 = 0x58, //It's Ok, you don't need to be scared.
        GAMETEXT_059_SW_Garunda_Te_chat_before_DIM_1 = 0x59, //Time is running out. You must find the Spellstone!
        GAMETEXT_05A_MMP_SharpClaw_lookout_launching_barrels = 0x5A, //Wake up!
        GAMETEXT_05B_SC_Krystal_meets_Rubble_1 = 0x5B, //Greetings stranger, my name is Rubble and I'm a SwapStone.
        GAMETEXT_05C_SW_Tricky_chases_after_SharpClaw = 0x5C, //Grrrrrr grrrrrr Sssh Keep quiet.
        GAMETEXT_05D_Debug_File_Not_Found = 0x5D, //Gametext requested is not there.
        GAMETEXT_05E_SH_Sabre_meets_Queen_EarthWalker_1 = 0x5E, //Tricky, what's happened?
        GAMETEXT_05F_SH_Sabre_meets_Queen_EarthWalker_2 = 0x5F, //We need to collect ten white mushrooms.
        GAMETEXT_060_SW_Garunda_Te_chat_before_activating_SpellStone = 0x60, //Where are you going boy, that spell stone is useless until I have activates it.
        GAMETEXT_061_SwapStone_Chat_15 = 0x61, //Hello Krystal.
        GAMETEXT_062_SwapStone_Chat_16 = 0x62, //Fairwell Krystal. Don't be a stranger.
        GAMETEXT_063_SwapStone_Chat_17 = 0x63, //Goodbye Krystal. Come back soon.
        GAMETEXT_064_SW_Trickys_commands = 0x64, //Tricky are you crazy. Just leave the SharpClaws to me.
        GAMETEXT_065_SB_CloudRunner_battle_tips_2 = 0x65, //Shoot the propeller. 
        GAMETEXT_066_SB_Kyte_calling_for_help_1 = 0x66, //Help....! 
        GAMETEXT_067_SB_Kyte_calling_for_help_2 = 0x67, //Somebody, get me out of here.
        GAMETEXT_068_SB_Kyte_calling_for_help_3 = 0x68, //Find the wizard and get me out of here.
        GAMETEXT_069_SB_CloudRunner_battle_tips_3 = 0x69, //Finish him, blast the head.
        GAMETEXT_06A_SB_Krystal_boarding_Galleon = 0x6A, //Tell the queen, I'll bring her daughter back to Cloudrunner Fortress.
        GAMETEXT_06B_SB_Confronting_Scales_1 = 0x6B, //General Scales, ruler, tyrant and dictator of the Sharpclaw tribe and who might you be, animal girl?
        GAMETEXT_06C_SB_Confronting_Scales_3 = 0x6C, //Ha ha, nice try,
        GAMETEXT_06D_SB_Confronting_Scales_2 = 0x6D, //How do you know the wizard?
        GAMETEXT_06E_SW_Grumpy_SnowHorn_chat_while_Tricky_chases_SharpClaw = 0x6E, //Humph. Shouldn't you help your friend!
        GAMETEXT_06F_SW_Grumpy_SnowHorn_chat_before_finding_Alpine_Root = 0x6F, //I'm too hungry to talk to strangers.
        GAMETEXT_070_SW_Grumpy_SnowHorn_chat_after_finding_Alpine_Root = 0x70, //If you press the  you can feed me that root you found.
        GAMETEXT_071_SW_Grumpy_SnowHorn_eats_1st_Alpine_Root = 0x71, //One root is never enough. I'm starving!
        GAMETEXT_072_SW_Grumpy_SnowHorn_eats_2nd_Alpine_Root = 0x72, //Aaaaahh. That hit the spot. Tell you what young 'un. I'll help you out.
        GAMETEXT_073_SW_Grumpy_SnowHorn_chat_after_2nd_root = 0x73, //I'm sorry lad you're on your own.
        GAMETEXT_074_WM_Randorn_and_Krystal_Meeting_Duplicate = 0x74, //Randorn, whats happened to you?
        GAMETEXT_075_WM_EarthWalker_crying_out = 0x75, //Help!
        GAMETEXT_076_WM_EarthWalker_dying = 0x76, //Try not to move, the wizard will help you.
        GAMETEXT_077_SB_Arriving_at_Warlock_Mountain_1 = 0x77, //I think we've stopped.
        GAMETEXT_078_SB_Arriving_at_Warlock_Mountain_3 = 0x78, //I'll go find the wizard, he'll get you out.
        GAMETEXT_079_SB_Arriving_at_Warlock_Mountain_2 = 0x79, //I'm sorry Kyte, I can't open the cage.
        GAMETEXT_07A_SB_Meeting_Kyte = 0x7A, //I'm OK, I think.
        GAMETEXT_07B_SW_Grumpy_SnowHorn_chat_after_1st_root = 0x7B, //One root is never enough. I'm starving!
        GAMETEXT_07C_DB_PointBack_peril_1 = 0x7C, //The water has flooded my nest!
        GAMETEXT_07D_DB_PointBack_peril_2 = 0x7D, //I'll wait further up the beach, please bring them to me.
        GAMETEXT_07E_DB_PointBack_peril_4 = 0x7E, //Hurry. The storm is getting worse.
        GAMETEXT_07F_DB_PointBack_peril_5 = 0x7F, //My babies!
        GAMETEXT_080_DB_PointBack_peril_6 = 0x80, //If only we had another chance.
        GAMETEXT_081_DB_PointBack_eggs_saved_1 = 0x81, //I've been saving this for you.
        GAMETEXT_082_SH_ThornTail_chat_8 = 0x82, //Have you woken the Swapstone yet.
        GAMETEXT_083_SH_ThornTail_chat_9 = 0x83, //Leave me alone stranger, I'm not moving.
        GAMETEXT_084_SH_ThornTail_chat_10 = 0x84, //Go away!
        GAMETEXT_085_SH_ThornTail_chat_11 = 0x85, //Why if it isn't the young Earthwalker.
        GAMETEXT_086_SH_ThornTail_chat_12 = 0x86, //Use the net to catch a fish.
        GAMETEXT_087_SH_ThornTail_chat_13 = 0x87, //Come back when you have my fish.
        GAMETEXT_088_SH_ThornTail_chat_14 = 0x88, //I'm too hungry to help you now, do you have any food.
        GAMETEXT_089_SH_ThornTail_chat_15 = 0x89, //I can help you, but not on an empty stomach.
        GAMETEXT_08A_SH_ThornTail_chat_16 = 0x8A, //The SharpClaws drained our river. Can you help us?
        GAMETEXT_08B_SH_ThornTail_chat_17 = 0x8B, //The river flows to Diamond bay.
        GAMETEXT_08C_SH_ThornTail_chat_18 = 0x8C, //If only these thorns were not blocking the burrows.
        GAMETEXT_08D_SH_ThornTail_chat_19 = 0x8D, //Things aren't like they used to be.
        GAMETEXT_08E_SH_Medicine_for_Queen_EarthWalker = 0x8E, //You must find more.
        GAMETEXT_08F_SH_Queen_EarthWalker_cured_1 = 0x8F, //Thank you Fox.
        GAMETEXT_090_SH_Queen_EarthWalker_cured_2 = 0x90, //That's Ok. Now, if you don't need me any further then I'll be off.
        GAMETEXT_091_SH_Queen_EarthWalker_cured_3 = 0x91, //Wait!
        GAMETEXT_092_SH_Queen_EarthWalker_cured_4 = 0x92, //This is a Force Point Temple.
        GAMETEXT_093_SH_Queen_EarthWalker_cured_5 = 0x93, //So why do you need me?
        GAMETEXT_094_SH_Queen_EarthWalker_cured_6 = 0x94, //When the temples were constructed, a shutdown mechanism was hidden within.
        GAMETEXT_095_SH_Queen_EarthWalker_cured_7 = 0x95, //Look, I'm sorry that you're in all of this trouble, I really am,
        GAMETEXT_096_SH_Queen_EarthWalker_cured_8 = 0x96, //What do you mean?
        GAMETEXT_097_SH_Queen_EarthWalker_cured_9 = 0x97, //C'mon Tricky let's get going.
        GAMETEXT_098_SH_Queen_EarthWalker_cured_10 = 0x98, //The Purple Mushrooms hold a special secret.
        GAMETEXT_099_SW_SnowHorn_chat_before_DIM_1 = 0x99, //Follow the path to SwapStone Hollow.
        GAMETEXT_09A_SW_SnowHorn_chat_before_DIM_2 = 0x9A, //Beyond the hollow lies the Prince's homelands.
        GAMETEXT_09B_SW_SnowHorn_chat_before_DIM_3 = 0x9B, //Do you hear that?
        GAMETEXT_09C_SW_SnowHorn_chat_before_DIM_4 = 0x9C, //The SharpClaws have captured our leader.
        GAMETEXT_09D_SH_ThornTail_chat_1 = 0x9D, //Do you have any food for me yet?
        GAMETEXT_09E_SH_ThornTail_chat_2 = 0x9E, //Pushing these logs around makes me hungry.
        GAMETEXT_09F_SH_ThornTail_chat_3 = 0x9F, //Moonseeds grow in dark damp places.
        GAMETEXT_0A0_SH_ThornTail_chat_4 = 0xA0, //Who keeps digging in my burrows?
        GAMETEXT_0A1_SH_ThornTail_chat_5 = 0xA1, //Have you got any food for me?
        GAMETEXT_0A2_SH_ThornTail_chat_6 = 0xA2, //Nobody should enter Willow Grove.
        GAMETEXT_0A3_SH_ThornTail_chat_7 = 0xA3, //My precious Lily grows again!
        GAMETEXT_0A4_SH_Sabre_meets_Rocky = 0xA4, //Hello there little fellow, I'm Rocky.
        GAMETEXT_0A5_SW_Sabre_meets_Tricky_1 = 0xA5, //You're lucky it's a hot spring or you'd be frozen by now.
        GAMETEXT_0A6_SW_Sabre_meets_Tricky_2 = 0xA6, //Hey, I wouldn't if I were you, my dad's a King EarthWalker and he'll bash you up!
        GAMETEXT_0A7_SW_Sabre_meets_Tricky_3 = 0xA7, //I don't think he'll be doing any bashing, he's been captured.
        GAMETEXT_0A8_CC_Krystal_rescues_Kyte_1 = 0xA8, //Krystal, you've found me!
        GAMETEXT_0A9_CC_Krystal_rescues_Kyte_2 = 0xA9, //Listen Krystal, I`ve learnt some new skills since we were last together.
        GAMETEXT_0AA_DIM_Shackled_SnowHorn_chat_1 = 0xAA, //Can you help me get free?
        GAMETEXT_0AB_DIM_Shackled_SnowHorn_chat_2 = 0xAB, //I cannot thank you enough for releasing me. Take this as a reward.
        GAMETEXT_0AC_SC_Krystal_meets_Rubble_2 = 0xAC, //Now, now ... Don't be scared.
        GAMETEXT_0AD_DIM_Learning_Flame_Command_1 = 0xAD, //I am forever in your debt.
        GAMETEXT_0AE_DIM_Learning_Flame_Command_2 = 0xAE, //Go on youngster, give it a go.
        GAMETEXT_0AF_DIM_Learning_Flame_Command_3 = 0xAF, //If I wasn't so exhausted, I could sneak you past the main gates.
        GAMETEXT_0B0_DIM_Famished_SnowHorn_chat_1 = 0xB0, //I need some food,
        GAMETEXT_0B1_DIM_Famished_SnowHorn_chat_2 = 0xB1, //That's better, but I need more.
        GAMETEXT_0B2_DIM_Famished_SnowHorn_chat_3 = 0xB2, //I'm so hungrey, I need food.
        GAMETEXT_0B3_DIM_Famished_SnowHorn_chat_4 = 0xB3, //I feel much better now.
        GAMETEXT_0B4_CC_Kyte_chat = 0xB4, //Thanks Krystal, it was terrible it that cell.
        GAMETEXT_0B5_DF_Food_Bag_tutorial_1 = 0xB5, //Do not hit SharpClaw,
        GAMETEXT_0B6_DF_Food_Bag_tutorial_2 = 0xB6, //You choose how use it.
        GAMETEXT_0B7_DF_Food_Bag_tutorial_3 = 0xB7, //I can always change this later.
        GAMETEXT_0B8_SC_LightFoot_ambush = 0xB8, //Baby lightfoot whimpers.
        GAMETEXT_0B9_SC_Krystal_wakes_after_ambush = 0xB9, //Thats the one.
        GAMETEXT_0BA_SW_SnowHorn_chat_before_DIM_1 = 0xBA, //Beware the depths of the mine, a monster hides in the ice!
        GAMETEXT_0BB_Tricky_Chat = 0xBB, //Can you find any blue mushrooms? I'm feeling real tired
        GAMETEXT_0BC_Tricky_Command_Responses_1 = 0xBC, //I'm too tired to do this right now
        GAMETEXT_0BD_Tricky_Command_Responses_2 = 0xBD, //It's too deep, I need more practice
        GAMETEXT_0BE_SW_Tricky_Tutorial_Hint = 0xBE, //Lets try out my find command
        GAMETEXT_0BF_SW_Trapped_under_ice = 0xBF, //They sent you to rescue me? ... Hmmpphh.
        GAMETEXT_0C0_SW_SnowHorn_chat_before_DIM_2 = 0xC0, //If you help our tribe I'm sure they'll reward you.
        GAMETEXT_0C1_SW_Freed_from_ice_1 = 0xC1, //Look out boy!
        GAMETEXT_0C2_SW_Freed_from_ice_2 = 0xC2, //Many moons in our past,
        GAMETEXT_0C3_SW_Freed_from_ice_3 = 0xC3, //Each Guardian was to keep this Knowledge secret.
        GAMETEXT_0C4_SW_Freed_from_ice_4 = 0xC4, //My daughter told scales that she knew
        GAMETEXT_0C5_SW_Freed_from_ice_5 = 0xC5, //Remember,you must return the spellstone to me,
        GAMETEXT_0C6_DIM_Horn_of_Truth_Chat_1 = 0xC6, //Across the ravine you will find our most sacred treasure, the Horn Of Truth.
        GAMETEXT_0C7_DIM_Horn_of_Truth_Chat_2 = 0xC7, //Believe in your quest Sabre, you must believe.
        GAMETEXT_0C8_DIM_Horn_of_Truth_Chat_3 = 0xC8, //Use the Horn wisely Sabre. It will summon help in times of need.
        GAMETEXT_0C9_CC_HighTop_Chat = 0xC9, //Be careful of the water, there are strong under currents.
        GAMETEXT_0CA_DIM_Meeting_Belina_Te_1 = 0xCA, //Who are you?
        GAMETEXT_0CB_DIM_Meeting_Belina_Te_2 = 0xCB, //Belina are you there?
        GAMETEXT_0CC_DR_Mind_Read_messages_1 = 0xCC, //No food been delivered , me starving!
        GAMETEXT_0CD_Mind_Read_messages_2 = 0xCD, //General Response of Mind Read
        GAMETEXT_0CE_DR_Mind_Read_messages_3 = 0xCE, //Ooh I am In Such Pain
        GAMETEXT_0CF_DR_Mind_Read_messages_4 = 0xCF, //I am sorry but I am afraid of the Dark.
        GAMETEXT_0D0_DR_Mind_Read_messages_5 = 0xD0, //Thank Heavens I am Out of There
        GAMETEXT_0D1_DR_Mind_Read_messages_6 = 0xD1, //I hate Earthwalkers especially Small Ones.
        GAMETEXT_0D2_Debug_Alternate_Entrance_Sequences_1 = 0xD2, //This is the standard entrance sequence.
        GAMETEXT_0D3_Debug_Alternate_Entrance_Sequences_2 = 0xD3, //This is the special entrance sequence.
        GAMETEXT_0D4_Shop_ShopKeeper_Chat_5 = 0xD4, //I hope you have learned from your previous mistakes.
        GAMETEXT_0D5_Shop_Hint_Well_1 = 0xD5, //Throw me a Scarab and I'll give some advice.
        GAMETEXT_0D6_Shop_Hint_Well_2 = 0xD6, //Chomp chomp... burp... Watch closely.
        GAMETEXT_0D7_DR_Finding_the_shackled_EarthWalker_1 = 0xD7, //Skeetlas!
        GAMETEXT_0D8_DR_Finding_the_shackled_EarthWalker_2 = 0xD8, //Come on Tricky, We've got to help him!
        GAMETEXT_0D9_Shop_Scarab_Game_4 = 0xD9, //I don't believe you did it! You win fair and square.
        GAMETEXT_0DA_Shop_ShopKeeper_Haggling_1 = 0xDA, //You pay this much
        GAMETEXT_0DB_Shop_ShopKeeper_Haggling_5 = 0xDB, //Put that down! You don't have enough Scarabs!
        GAMETEXT_0DC_Shop_ShopKeeper_Haggling_2 = 0xDC, //NO,That's too low
        GAMETEXT_0DD_Shop_ShopKeeper_Haggling_3 = 0xDD, //OK I'll sell it to you.
        GAMETEXT_0DE_Shop_ShopKeeper_Haggling_4 = 0xDE, //I don't need business from cheapskates!
        GAMETEXT_0DF_Shop_ShopKeeper_Chat_1 = 0xDF, //Feel free to look around.
        GAMETEXT_0E0_Shop_ShopKeeper_Chat_2 = 0xE0, //There are many surprises within my store.
        GAMETEXT_0E1_Shop_ShopKeeper_Chat_3 = 0xE1, //Hurry and choose something or get out.
        GAMETEXT_0E2_Shop_ShopKeeper_Chat_4 = 0xE2, //You do not have enough Scarabs to enter.
        GAMETEXT_0E3_Shop_Scarab_Game_1 = 0xE3, //How about playing a little game?
        GAMETEXT_0E4_Shop_Scarab_Game_3 = 0xE4, //Aaaaa Haa HAAA!
        GAMETEXT_0E5_Shop_Scarab_Game_2 = 0xE5, //Are you ready?
        GAMETEXT_0E6_SC_LightFoot_Trials_Strength = 0xE6, //Your final challenge!
        GAMETEXT_0E7_DR_Saving_the_shackled_EarthWalker = 0xE7, //Thanks for helping me,
        GAMETEXT_0E8_DR_Skeetlas_return = 0xE8, //Don't you think we should be getting out from here.
        GAMETEXT_0E9_DR_Freeing_the_EarthWalker_ascending_on_lift = 0xE9, //You are very brave to help us Sabre.
        GAMETEXT_0EA_SW_SnowHorn_chat_before_activating_SpellStone_1 = 0xEA, //Hey, Shouldn't you get that SpellStone activated?
        GAMETEXT_0EB_SH_SwapStone_Tutorial = 0xEB, //If you push left on the joystick
        GAMETEXT_0EC_Menu_Managing_Saves = 0xEC, //A-SELECT B-CANCEL
        GAMETEXT_0ED_Menu_Name_Entry = 0xED, //A
        GAMETEXT_0EE_Menu_Title_Screen = 0xEE, //< ENGLISH >
        GAMETEXT_0EF_Menu_Main_Menu = 0xEF, //A-SELECT B-CANCEL
        GAMETEXT_0F0_DR_Freeing_the_CloudRunner_1 = 0xF0, //Look Out!
        GAMETEXT_0F1_DR_Freeing_the_CloudRunner_2 = 0xF1, //Are you OK?
        GAMETEXT_0F2_Splash_Screen = 0xF2, //EXPANSION PAK - DETECTED
        GAMETEXT_0F3_Expansion_Pak_Needed = 0xF3, //N64 EXPANSION PAK² NOT INSTALLED.
        GAMETEXT_0F4_Task_Header = 0xF4, //SUB TASK
        GAMETEXT_0F5_Task_001 = 0xF5, //DEFEATED GENERAL SCALES GALLEON
        GAMETEXT_0F6_Task_002 = 0xF6, //FOUND PRINCESS KYTE
        GAMETEXT_0F7_Task_003 = 0xF7, //FOUND RANDORN AND COLLECTED PROJECTILE SPELL
        GAMETEXT_0F8_Task_004 = 0xF8, //COLLECTED WARP CRYSTAL
        GAMETEXT_0F9_Task_005 = 0xF9, //PLACE WARP CRYSTAL
        GAMETEXT_0FA_Task_006 = 0xFA, //WARPED TO SWAPSTONE
        GAMETEXT_0FB_Task_007 = 0xFB, //FREED PRINCE EARTHWALKER FROM THE SHARPCLAW
        GAMETEXT_0FC_Task_008 = 0xFC, //WON ICE MOUNTAIN RACE
        GAMETEXT_0FD_Task_009 = 0xFD, //TRICKY DUG TUNNEL OUT OF TRAINING AREA
        GAMETEXT_0FE_Task_010 = 0xFE, //FOUND ENTRANCE TO SWAPSTONE HOLLOW
        GAMETEXT_0FF_Task_011 = 0xFF, //FOUND QUEEN EARTHWALKER
        GAMETEXT_100_Task_012 = 0x100, //COLLECTED 10 WHITE MUSHROOMS
        GAMETEXT_101_Task_013 = 0x101, //MET THE SWAPSTONE
        GAMETEXT_102_Task_014 = 0x102, //SWAPPED TO KRYSTAL
        GAMETEXT_103_Task_015 = 0x103, //ENTERED CAPE CLAW BY BRIBING GUARDCLAW
        GAMETEXT_104_Task_016 = 0x104, //FREED LIGHTFOOT AND COLLECTED FORCEFIELD SPELL
        GAMETEXT_105_Task_017 = 0x105, //RESCUED PRINCESS KYTE
        GAMETEXT_106_Task_018 = 0x106, //EXITED CAPE CLAW COURTYARD
        GAMETEXT_107_Task_019 = 0x107, //DEFEATED THE LIGHTFOOT
        GAMETEXT_108_Task_020 = 0x108, //LIT BEACONS FOR CHIEF LIGHTFOOT
        GAMETEXT_109_Task_021 = 0x109, //ENTERED DISCOVERY FALLS
        GAMETEXT_10A_Task_022 = 0x10A, //OPENED DISCOVERY FALLS KRAZOA SHRINE
        GAMETEXT_10B_Task_023 = 0x10B, //ENTERED DISCOVERY FALLS KRAZOA SHRINE
        GAMETEXT_10C_Task_024 = 0x10C, //COMPLETE TEST OF COMBAT AND COLLECTED KRAZOA SPIRIT
        GAMETEXT_10D_Task_025 = 0x10D, //RETURNED TO SWAPSTONE AND WARPED TO WARLOCK
        GAMETEXT_10E_Task_026 = 0x10E, //RELEASED FIRST KRAZOA SPIRIT!
        GAMETEXT_10F_Task_027 = 0x10F, //SWAPPED TO SABRE
        GAMETEXT_110_Task_028 = 0x110, //FOUND SNOWHORN GUARDIAN
        GAMETEXT_111_Task_029 = 0x111, //RELEASED SNOWHORN GUARDIAN
        GAMETEXT_112_Task_030 = 0x112, //ENTERED DIM
        GAMETEXT_113_Task_031 = 0x113, //UNCHAINED SNOWHORN
        GAMETEXT_114_Task_032 = 0x114, //RODE SNOWHORN THROUGH MAIN GATES
        GAMETEXT_115_Task_033 = 0x115, //ACTIVATED BRIDGE
        GAMETEXT_116_Task_034 = 0x116, //COLLECTED THE HORN OF TRUTH
        GAMETEXT_117_Task_035 = 0x117, //RODE SNOWHORN THROUGH BLIZZARD
        GAMETEXT_118_Task_036 = 0x118, //RODE JETBIKE INTO MINE
        GAMETEXT_119_Task_037 = 0x119, //FOUND THE GUARDIAN'S DAUGHTER
        GAMETEXT_11A_Task_038 = 0x11A, //REACHED THE BOTTOM OF THE MINE
        GAMETEXT_11B_Task_039 = 0x11B, //ENTERED DARKICE BOSS LEVEL
        GAMETEXT_11C_Task_040 = 0x11C, //DEFEATED BOSS AND COLLECTED FIRST SPELLSTONE
        GAMETEXT_11D_Task_041 = 0x11D, //RETURNED TO SNOWHORN GUARDIAN
        GAMETEXT_11E_Task_042 = 0x11E, //GUARDIAN ACTVIATED THE SPELLSTONE
        GAMETEXT_11F_Task_043 = 0x11F, //BOUGHT LOG FROM A THORNTAIL
        GAMETEXT_120_Task_044 = 0x120, //ENTERED DIAMOND BAY
        GAMETEXT_121_Task_045 = 0x121, //DISCOVERED POINTBACK
        GAMETEXT_122_Task_046 = 0x122, //RECOVERED POINTBACK EGG
        GAMETEXT_123_Task_047 = 0x123, //GAINED ACCESS TO VOLCANO AREA
        GAMETEXT_124_Task_048 = 0x124, //ENTERED VOLCANO FORCEPOINT TEMPLE
        GAMETEXT_125_Task_049 = 0x125, //OPENED FIRST PATH THROUGH TEMPLE
        GAMETEXT_126_Task_050 = 0x126, //PLACED THE FIRST SPELLSTONE!!
        GAMETEXT_127_Task_051 = 0x127, //OPENED DIAMOND BAY KRAZOA SHRINE
        GAMETEXT_128_Task_052 = 0x128, //COMPLETED TEST OF STRENGTH AND COLLECTED KRAZOA SPIRIT
        GAMETEXT_129_Task_053 = 0x129, //RETURNED TO SWAPSTONE HOLLOW AND WARPED TO WARLOCK MOUNTAIN
        GAMETEXT_12A_Task_054 = 0x12A, //RELEASED THE SECOND SPIRIT IN WARLOCK MOUNTAIN
        GAMETEXT_12B_Task_055 = 0x12B, //TASK 55 NAME
        GAMETEXT_12C_Task_056 = 0x12C, //CHIEF GIVES YOU MOON MOUNTAIN PASS KEY
        GAMETEXT_12D_Task_057 = 0x12D, //ENTERED MOON MOUNTAIN PASS
        GAMETEXT_12E_Task_058 = 0x12E, //GOT PASSED SHARPCLAWS AND THEIR BARRELS!
        GAMETEXT_12F_Task_059 = 0x12F, //ENTERED CLOUDRUNNER FORTRESS
        GAMETEXT_130_Task_060 = 0x130, //GENERAL SCALES KILLS KYTE'S MOTHER
        GAMETEXT_131_Task_061 = 0x131, //FREED BONEHEAD AND ESCAPED FROM DUNGEON
        GAMETEXT_132_Task_062 = 0x132, //RE-ACTIVATED POWER WITHIN THE FORTRESS
        GAMETEXT_133_Task_063 = 0x133, //RESCUED KYTE
        GAMETEXT_134_Task_064 = 0x134, //RESCUED 5 BABY CLOUDRUNNERS
        GAMETEXT_135_Task_065 = 0x135, //STOPPED THE SHARPCLAWS RANSACKING THE GOLD!
        GAMETEXT_136_Task_066 = 0x136, //ENTERED THE TREASURE CAVES UNDER THE FORTRESS
        GAMETEXT_137_Task_067 = 0x137, //RACED ON JETBIKE AND RETRIEVED THE SPELLSTONE
        GAMETEXT_138_Task_068 = 0x138, //BONEHEAD ACTIVATES THE SPELLSTONE
        GAMETEXT_139_Task_069 = 0x139, //ENTERED GOLDEN PLAINS
        GAMETEXT_13A_Task_070 = 0x13A, //COLLECTED PORTABLE HOLE SPELL
        GAMETEXT_13B_Task_071 = 0x13B, //ENTERED THE DESERT FORCE POINT TEMPLE
        GAMETEXT_13C_Task_072 = 0x13C, //SHUTDOWN THE POWER FLOW
        GAMETEXT_13D_Task_073 = 0x13D, //PLACE THE 2ND SPELLSTONE
        GAMETEXT_13E_Task_074 = 0x13E, //WITNESSED THE MIRAGE AND SWAPPED BACK TO SABRE
        GAMETEXT_13F_Task_075 = 0x13F, //ENTERED WALLED CITY
        GAMETEXT_140_Task_076 = 0x140, //QUEEN EARTHWALKER TELLS YOU WHAT TO DO
        GAMETEXT_141_Task_077 = 0x141, //TRICKY'S FLAME BEGINS THE CHASE!
        GAMETEXT_142_Task_078 = 0x142, //COLLECTED 10 TEETH TO ENTER THE CITY
        GAMETEXT_143_Task_079 = 0x143, //FOUND THE KING EARTHWALKER
        GAMETEXT_144_Task_080 = 0x144, //LIGHT SUN AND MOON BEACONS
        GAMETEXT_145_Task_081 = 0x145, //USED REDEYE TEETH TO OPEN BOSS DOOR
        GAMETEXT_146_Task_082 = 0x146, //DEFEATED REDEYE BOSS AND COLLECTED SPELLSTONE
        GAMETEXT_147_Task_083 = 0x147, //KING EARTHWALKER ACTIVATES THE SPELLSTONE
        GAMETEXT_148_Task_084 = 0x148, //BOUGHT ANOTHER LOG FROM THE THORNTAIL
        GAMETEXT_149_Task_085 = 0x149, //ENTERED DIAMOND BAY
        GAMETEXT_14A_Task_086 = 0x14A, //FOUND THE POINTBACK
        GAMETEXT_14B_Task_087 = 0x14B, //FOUND THE SECOND POINTBACK EGG
        GAMETEXT_14C_Task_088 = 0x14C, //OPENED ROUTE INTO THE VOLCANO
        GAMETEXT_14D_Task_089 = 0x14D, //USED SPELLSTONE TO OPEN 2ND PATH IN VOLCANO
        GAMETEXT_14E_Task_090 = 0x14E, //PLACED THE THIRD SPELLSTONE
        GAMETEXT_14F_Task_091 = 0x14F, //COLLECTED MOONSEEDS FOR KRYSTAL
        GAMETEXT_150_Task_092 = 0x150, //SWAPPED TO KRYSTAL
        GAMETEXT_151_Task_093 = 0x151, //RETURNED TO MOON MOUNTAIN PASS AND PLANTED SEED
        GAMETEXT_152_Task_094 = 0x152, //MOVED METEOR TO REACH SHRINE ENTRANCE
        GAMETEXT_153_Task_095 = 0x153, //COMPLETED THE TEST OF FEAR AND COLLECTED KRAZOA SPIRIT
        GAMETEXT_154_Task_096 = 0x154, //WARPED BACK TO WARLOCK MOUNTAIN WITH THE SPIRIT
        GAMETEXT_155_Task_097 = 0x155, //RELEASED THE THIRD KRAZOA SPIRIT
        GAMETEXT_156_Task_098 = 0x156, //SWAPPED BACK TO SABRE
        GAMETEXT_157_Task_099 = 0x157, //ENTERED WALLED CITY
        GAMETEXT_158_Task_100 = 0x158, //COLLECTED THE SUNSTONE
        GAMETEXT_159_Task_101 = 0x159, //COLLECTED THE MOONSTONE
        GAMETEXT_15A_Task_102 = 0x15A, //USED SUN AND MOON STONES TO OPEN SHRINE
        GAMETEXT_15B_Task_103 = 0x15B, //COMPLETED THE TEST OF SKILL
        GAMETEXT_15C_Task_104 = 0x15C, //RETURNED TO WARLOCK MOUNTAIN WITH THE SPIRIT
        GAMETEXT_15D_Task_105 = 0x15D, //RELEASED THE FOURTH KRAZOA SPIRIT
        GAMETEXT_15E_Task_106 = 0x15E, //SWAPPED TO KRYSTAL
        GAMETEXT_15F_Task_107 = 0x15F, //TASK 107 NAME
        GAMETEXT_160_Task_108 = 0x160, //TASK 108 NAME
        GAMETEXT_161_Task_109 = 0x161, //TASK 109 NAME
        GAMETEXT_162_Task_110 = 0x162, //TASK 110 NAME
        GAMETEXT_163_Task_111 = 0x163, //TASK 111 NAME
        GAMETEXT_164_Task_112 = 0x164, //TASK 112 NAME
        GAMETEXT_165_Task_113 = 0x165, //TASK 113 NAME
        GAMETEXT_166_Task_114 = 0x166, //TASK 114 NAME
        GAMETEXT_167_Task_115 = 0x167, //TASK 115 NAME
        GAMETEXT_168_Task_116 = 0x168, //TASK 116 NAME
        GAMETEXT_169_Task_117 = 0x169, //TASK 117 NAME
        GAMETEXT_16A_Task_118 = 0x16A, //TASK 118 NAME
        GAMETEXT_16B_Task_119 = 0x16B, //TASK 119 NAME
        GAMETEXT_16C_Task_120 = 0x16C, //TASK 120 NAME
        GAMETEXT_16D_Task_121 = 0x16D, //TASK 121 NAME
        GAMETEXT_16E_Task_122 = 0x16E, //TASK 122 NAME
        GAMETEXT_16F_Task_123 = 0x16F, //TASK 123 NAME
        GAMETEXT_170_Task_124 = 0x170, //TASK 124 NAME
        GAMETEXT_171_Task_125 = 0x171, //TASK 125 NAME
        GAMETEXT_172_Task_126 = 0x172, //TASK 126 NAME
        GAMETEXT_173_Task_127 = 0x173, //TASK 127 NAME
        GAMETEXT_174_Task_128 = 0x174, //TASK 128 NAME
        GAMETEXT_175_Task_129 = 0x175, //TASK 129 NAME
        GAMETEXT_176_Task_130 = 0x176, //TASK 130 NAME
        GAMETEXT_177_Task_131 = 0x177, //TASK 131 NAME
        GAMETEXT_178_Task_132 = 0x178, //TASK 132 NAME
        GAMETEXT_179_Task_133 = 0x179, //TASK 133 NAME
        GAMETEXT_17A_Task_134 = 0x17A, //TASK 134 NAME
        GAMETEXT_17B_Task_135 = 0x17B, //TASK 135 NAME
        GAMETEXT_17C_Task_136 = 0x17C, //TASK 136 NAME
        GAMETEXT_17D_Task_137 = 0x17D, //TASK 137 NAME
        GAMETEXT_17E_Task_138 = 0x17E, //TASK 138 NAME
        GAMETEXT_17F_Task_139 = 0x17F, //TASK 139 NAME
        GAMETEXT_180_Task_140 = 0x180, //TASK 140 NAME
        GAMETEXT_181_Task_141 = 0x181, //TASK 141 NAME
        GAMETEXT_182_Task_142 = 0x182, //TASK 142 NAME
        GAMETEXT_183_Task_143 = 0x183, //TASK 143 NAME
        GAMETEXT_184_Task_144 = 0x184, //TASK 144 NAME
        GAMETEXT_185_Task_145 = 0x185, //TASK 145 NAME
        GAMETEXT_186_Task_146 = 0x186, //TASK 146 NAME
        GAMETEXT_187_Task_147 = 0x187, //TASK 147 NAME
        GAMETEXT_188_Task_148 = 0x188, //TASK 148 NAME
        GAMETEXT_189_Task_149 = 0x189, //TASK 149 NAME
        GAMETEXT_18A_Task_150 = 0x18A, //TASK 150 NAME
        GAMETEXT_18B_Task_151 = 0x18B, //TASK 151 NAME
        GAMETEXT_18C_Task_152 = 0x18C, //TASK 152 NAME
        GAMETEXT_18D_Task_153 = 0x18D, //TASK 153 NAME
        GAMETEXT_18E_Task_154 = 0x18E, //TASK 154 NAME
        GAMETEXT_18F_Task_155 = 0x18F, //TASK 155 NAME
        GAMETEXT_190_Task_156 = 0x190, //TASK 156 NAME
        GAMETEXT_191_Task_157 = 0x191, //TASK 157 NAME
        GAMETEXT_192_Task_158 = 0x192, //TASK 158 NAME
        GAMETEXT_193_Task_159 = 0x193, //TASK 159 NAME
        GAMETEXT_194_Task_160 = 0x194, //TASK 160 NAME
        GAMETEXT_195_Task_161 = 0x195, //TASK 161 NAME
        GAMETEXT_196_Task_162 = 0x196, //TASK 162 NAME
        GAMETEXT_197_Task_163 = 0x197, //TASK 163 NAME
        GAMETEXT_198_Task_164 = 0x198, //TASK 164 NAME
        GAMETEXT_199_Task_165 = 0x199, //TASK 165 NAME
        GAMETEXT_19A_Task_166 = 0x19A, //TASK 166 NAME
        GAMETEXT_19B_Task_167 = 0x19B, //TASK 167 NAME
        GAMETEXT_19C_Task_168 = 0x19C, //TASK 168 NAME
        GAMETEXT_19D_Task_169 = 0x19D, //TASK 169 NAME
        GAMETEXT_19E_Task_170 = 0x19E, //TASK 170 NAME
        GAMETEXT_19F_Task_171 = 0x19F, //TASK 171 NAME
        GAMETEXT_1A0_Task_172 = 0x1A0, //TASK 172 NAME
        GAMETEXT_1A1_Task_173 = 0x1A1, //TASK 173 NAME
        GAMETEXT_1A2_Task_174 = 0x1A2, //TASK 174 NAME
        GAMETEXT_1A3_Task_175 = 0x1A3, //TASK 175 NAME
        GAMETEXT_1A4_Task_176 = 0x1A4, //TASK 176 NAME
        GAMETEXT_1A5_Task_177 = 0x1A5, //TASK 177 NAME
        GAMETEXT_1A6_Task_178 = 0x1A6, //TASK 178 NAME
        GAMETEXT_1A7_Task_179 = 0x1A7, //TASK 179 NAME
        GAMETEXT_1A8_Task_180 = 0x1A8, //TASK 180 NAME
        GAMETEXT_1A9_Task_181 = 0x1A9, //TASK 181 NAME
        GAMETEXT_1AA_Task_182 = 0x1AA, //TASK 182 NAME
        GAMETEXT_1AB_Task_183 = 0x1AB, //TASK 183 NAME
        GAMETEXT_1AC_Task_184 = 0x1AC, //TASK 184 NAME
        GAMETEXT_1AD_Task_185 = 0x1AD, //TASK 185 NAME
        GAMETEXT_1AE_Task_186 = 0x1AE, //TASK 186 NAME
        GAMETEXT_1AF_Task_187 = 0x1AF, //TASK 187 NAME
        GAMETEXT_1B0_Task_188 = 0x1B0, //TASK 188 NAME
        GAMETEXT_1B1_Task_189 = 0x1B1, //TASK 189 NAME
        GAMETEXT_1B2_Task_190 = 0x1B2, //TASK 190 NAME
        GAMETEXT_1B3_Task_191 = 0x1B3, //TASK 191 NAME
        GAMETEXT_1B4_Task_192 = 0x1B4, //TASK 192 NAME
        GAMETEXT_1B5_Task_193 = 0x1B5, //TASK 193 NAME
        GAMETEXT_1B6_Task_194 = 0x1B6, //TASK 194 NAME
        GAMETEXT_1B7_Task_195 = 0x1B7, //TASK 195 NAME
        GAMETEXT_1B8_Task_196 = 0x1B8, //TASK 196 NAME
        GAMETEXT_1B9_Task_197 = 0x1B9, //TASK 197 NAME
        GAMETEXT_1BA_Task_198 = 0x1BA, //TASK 198 NAME
        GAMETEXT_1BB_Task_199 = 0x1BB, //TASK 199 NAME
        GAMETEXT_1BC_Task_200 = 0x1BC, //TASK 200 NAME
        GAMETEXT_1BD_Task_201 = 0x1BD, //TASK 201 NAME
        GAMETEXT_1BE_Task_202 = 0x1BE, //TASK 202 NAME
        GAMETEXT_1BF_Task_203 = 0x1BF, //TASK 203 NAME
        GAMETEXT_1C0_Task_204 = 0x1C0, //TASK 204 NAME
        GAMETEXT_1C1_Task_205 = 0x1C1, //TASK 205 NAME
        GAMETEXT_1C2_Task_206 = 0x1C2, //TASK 206 NAME
        GAMETEXT_1C3_Task_207 = 0x1C3, //TASK 207 NAME
        GAMETEXT_1C4_Task_208 = 0x1C4, //TASK 208 NAME
        GAMETEXT_1C5_Task_209 = 0x1C5, //TASK 209 NAME
        GAMETEXT_1C6_Task_210 = 0x1C6, //TASK 210 NAME
        GAMETEXT_1C7_Task_211 = 0x1C7, //TASK 211 NAME
        GAMETEXT_1C8_Task_212 = 0x1C8, //TASK 212 NAME
        GAMETEXT_1C9_Task_213 = 0x1C9, //TASK 213 NAME
        GAMETEXT_1CA_Task_214 = 0x1CA, //TASK 214 NAME
        GAMETEXT_1CB_Task_215 = 0x1CB, //TASK 215 NAME
        GAMETEXT_1CC_Task_216 = 0x1CC, //TASK 216 NAME
        GAMETEXT_1CD_Task_217 = 0x1CD, //TASK 217 NAME
        GAMETEXT_1CE_Task_218 = 0x1CE, //TASK 218 NAME
        GAMETEXT_1CF_Task_219 = 0x1CF, //TASK 219 NAME
        GAMETEXT_1D0_Task_220 = 0x1D0, //TASK 220 NAME
        GAMETEXT_1D1_Task_221 = 0x1D1, //TASK 221 NAME
        GAMETEXT_1D2_Task_222 = 0x1D2, //TASK 222 NAME
        GAMETEXT_1D3_Task_223 = 0x1D3, //TASK 223 NAME
        GAMETEXT_1D4_Task_224 = 0x1D4, //TASK 224 NAME
        GAMETEXT_1D5_Task_225 = 0x1D5, //TASK 225 NAME
        GAMETEXT_1D6_Task_226 = 0x1D6, //TASK 226 NAME
        GAMETEXT_1D7_Task_227 = 0x1D7, //TASK 227 NAME
        GAMETEXT_1D8_Task_228 = 0x1D8, //TASK 228 NAME
        GAMETEXT_1D9_Task_229 = 0x1D9, //TASK 229 NAME
        GAMETEXT_1DA_Task_230 = 0x1DA, //TASK 220 NAME
        GAMETEXT_1DB_Task_231 = 0x1DB, //TASK 231 NAME
        GAMETEXT_1DC_Task_232 = 0x1DC, //TASK 232 NAME
        GAMETEXT_1DD_Task_233 = 0x1DD, //TASK 233 NAME
        GAMETEXT_1DE_Task_234 = 0x1DE, //TASK 234 NAME
        GAMETEXT_1DF_Task_235 = 0x1DF, //TASK 235 NAME
        GAMETEXT_1E0_Task_236 = 0x1E0, //TASK 236 NAME
        GAMETEXT_1E1_Task_237 = 0x1E1, //TASK 237 NAME
        GAMETEXT_1E2_Task_238 = 0x1E2, //TASK 238 NAME
        GAMETEXT_1E3_Task_239 = 0x1E3, //TASK 239 NAME
        GAMETEXT_1E4_Task_240 = 0x1E4, //TASK 240 NAME
        GAMETEXT_1E5_Task_241 = 0x1E5, //TASK 241 NAME
        GAMETEXT_1E6_Task_242 = 0x1E6, //TASK 242 NAME
        GAMETEXT_1E7_Task_243 = 0x1E7, //TASK 243 NAME
        GAMETEXT_1E8_Task_244 = 0x1E8, //TASK 244 NAME
        GAMETEXT_1E9_Task_245 = 0x1E9, //TASK 245 NAME
        GAMETEXT_1EA_Task_246 = 0x1EA, //TASK 246 NAME
        GAMETEXT_1EB_Task_247 = 0x1EB, //TASK 247 NAME
        GAMETEXT_1EC_Task_248 = 0x1EC, //TASK 248 NAME
        GAMETEXT_1ED_Task_249 = 0x1ED, //TASK 249 NAME
        GAMETEXT_1EE_Task_250 = 0x1EE, //TASK 250 NAME
        GAMETEXT_1EF_Task_251 = 0x1EF, //TASK 251 NAME
        GAMETEXT_1F0_Task_252 = 0x1F0, //TASK 252 NAME
        GAMETEXT_1F1_Task_253 = 0x1F1, //TASK 253 NAME
        GAMETEXT_1F2_Task_254 = 0x1F2, //TASK 254 NAME
        GAMETEXT_1F3_Task_255 = 0x1F3, //TASK 255 NAME
        GAMETEXT_1F4_DR_HighTop_opens_the_way = 0x1F4, //It's up to you guys now. You'll figure it out.
        GAMETEXT_1F5_Menu_Controls = 0x1F5, //A BUTTON
        GAMETEXT_1F6_Menu_Cheats = 0x1F6, //BIG HEAD
        GAMETEXT_1F7_Menu_Cinema = 0x1F7, //CINEMA 1
        GAMETEXT_1F8_DR_Freeing_the_HighTop = 0x1F8, //I guess we're ready to go.
        GAMETEXT_1F9_DFPT_Bridge_Codes_1 = 0x1F9, //BridgeCode1 Downloaded !
        GAMETEXT_1FA_DFPT_Bridge_Codes_2 = 0x1FA, //BridgeCode1 Uploaded !
        GAMETEXT_1FB_DFPT_Bridge_Codes_3 = 0x1FB, //BridgeCode2 Downloaded !
        GAMETEXT_1FC_DFPT_Bridge_Codes_4 = 0x1FC, //BridgeCode2 Uploaded !
        GAMETEXT_1FD_Credits = 0x1FD, //SOFTWARE DIRECTOR
        GAMETEXT_1FE_DR_Escape_collecting_the_SpellStone = 0x1FE, //You got it!
        GAMETEXT_1FF_SwapStone_Menu = 0x1FF, //WARP
        GAMETEXT_200_Death_Screen = 0x200, //CONTINUE
        GAMETEXT_201_DF_The_HighTops_gift = 0x201, //I took this before the Sharpclaw could get their hands on it.
        GAMETEXT_202_DR_Sabre_entering_Dragon_Rock = 0x202, //Good luck.
        GAMETEXT_203_DFPT_Scales_defeated_1 = 0x203, //I wouldn`t do that.
        GAMETEXT_204_DFPT_Scales_defeated_2 = 0x204, //Oh no
        GAMETEXT_205_WC_Meeting_King_EarthWalker = 0x205, //Dad, dad you're Ok!
        GAMETEXT_206_DR_Confronted_by_Drakor_1 = 0x206, //I can taste your fear animal 
        GAMETEXT_207_DR_Confronted_by_Drakor_2 = 0x207, //Even though the Dinosaurs believe in the Kamerian Dragon?
        GAMETEXT_208_DR_Confronted_by_Drakor_3 = 0x208, //You are more foolish than I thought
        GAMETEXT_209_DR_Confronted_by_Drakor_4 = 0x209, //You talk of destruction and evil without once mentioning yourself
        GAMETEXT_20A_WC_Tricky_sees_SpellStone = 0x20A, //Have you got it?
        GAMETEXT_20B_WC_King_EarthWalker_activates_SpellStone_1 = 0x20B, //Dad, Look waht we've got.
        GAMETEXT_20C_WC_King_EarthWalker_activates_SpellStone_2 = 0x20C, //Time to go, your mother will be waiting.
        GAMETEXT_20D_DB_Beginning_PointBack_2nd_egg_quest_1 = 0x20D, //Another SpellStone. You are doing very well.
        GAMETEXT_20E_SW_Garunda_Te_activates_SpellStone = 0x20E, //You would not believe what we had to do to get this!
        GAMETEXT_20F_DB_Meeting_the_PointBack_2 = 0x20F, //Bring this egg to me and I'll ... point ... you in the right direction ... point!
        GAMETEXT_210_SW_SnowHorn_chat_before_activating_SpellStone_2 = 0x210, //After all that hard work you have to let the Guardian do his work!
        GAMETEXT_211_SW_SnowHorn_chat_after_activating_SpellStone_1 = 0x211, //Take the SpellStone to Volcano Force Point.
        GAMETEXT_212_SW_SnowHorn_chat_after_activating_SpellStone_2 = 0x212, //As your journey ends you will meet us again.
        GAMETEXT_213_SW_SnowHorn_chat_Reward = 0x213, //You did such a good job you deserve this.
        GAMETEXT_214_SW_SnowHorn_chat_after_activating_SpellStone_3 = 0x214, //When you are ready, the sacred lands await.
        GAMETEXT_215_SW_SnowHorn_chat_Ice_Cave_trials_1 = 0x215, //The Ice Cave holds many dangers
        GAMETEXT_216_SW_SnowHorn_chat_Ice_Cave_trials_2 = 0x216, //Do not always believe what your eyes tell you is truth
        GAMETEXT_217_SW_SnowHorn_chat_Ice_Cave_trials_3 = 0x217, //Fighting isn't always the answer
        GAMETEXT_218_SW_SnowHorn_chat_Ice_Cave_trials_4 = 0x218, //Your final test awaits
        GAMETEXT_219_WC_Queen_EarthWalker_leads_the_way_1 = 0x219, //Mother! Mother!
        GAMETEXT_21A_WC_Queen_EarthWalker_leads_the_way_2 = 0x21A, //It's good to see you again Sabre.
        GAMETEXT_21B_WC_Queen_EarthWalker_leads_the_way_3 = 0x21B, //Stay with Sabre as far as the wall.
        GAMETEXT_21C_SH_Rocky_teaches_Distract_Command = 0x21C, //I think the Prince EarthWalker is ready for a new skill.
        GAMETEXT_21D_Empty = 0x21D,
        GAMETEXT_21E_Empty = 0x21E,
        GAMETEXT_21F_Empty = 0x21F,
        GAMETEXT_220_DB_Sabre_discovers_Shrine = 0x220, //A Krazoa Shrine! We have to get inside and collect the Quan Ata Lachu.
        GAMETEXT_221_DB_Sabre_exits_Shrine = 0x221, //Look Out, Sabre!
        GAMETEXT_222_DB_Returning_PointBacks_1st_egg_receiving_Diamond = 0x222, //Take this to the Volcano Gateway.
        GAMETEXT_223_DB_Beginning_PointBack_2nd_egg_quest_2 = 0x223, //Another SpellStone. You are doing very well.
        GAMETEXT_224_DB_Beginning_PointBack_3rd_egg_quest = 0x224, //The final SpellStone. Your quest is almost at an end.
        GAMETEXT_225_Empty = 0x225,
        GAMETEXT_226_CC_GuardClaw_Attempting_bribe = 0x226, //Hmmm.. I want more than just Scarabs.
        GAMETEXT_227_Title_Card_Diamond_Bay = 0x227,
        GAMETEXT_228_Title_Card_CloudRunner_Fortress = 0x228,
        GAMETEXT_229_Title_Card_Dragon_Rock = 0x229,
        GAMETEXT_22A_Title_Card_Volcano_Force_Point_Temple = 0x22A,
        GAMETEXT_22B_Title_Card_Discovery_Falls = 0x22B,
        GAMETEXT_22C_Title_Card_Moon_Mountain_Pass = 0x22C,
        GAMETEXT_22D_Title_Card_Desert_Force_Point_Temple = 0x22D,
        GAMETEXT_22E_Title_Card_Warlock_Mountain = 0x22E,
        GAMETEXT_22F_Title_Card_SnowHorn_Wastes = 0x22F, 
        GAMETEXT_230_Title_Card_SwapStone_Circle = 0x230,
        GAMETEXT_231_Title_Card_SwapStone_Hollow = 0x231,
        GAMETEXT_232_Title_Card_Golden_Plains = 0x232,
        GAMETEXT_233_Empty = 0x233, //BWC?
        GAMETEXT_234_Title_Card_Cape_Claw = 0x234,
        GAMETEXT_235_Title_Card_Boss_Galadon = 0x235,
        GAMETEXT_236_Title_Card_Boss_Klanadack = 0x236,
        GAMETEXT_237_Title_Card_Boss_Drakor = 0x237,
        GAMETEXT_238_UI_Text_2 = 0x238, //SCARABS
        GAMETEXT_239_DF_Arrival_Kyte_Flying = 0x239, //So this is Discovery Falls!
        GAMETEXT_23A_DFPT_Kyte_reactions_1 = 0x23A, //Krystal..
        GAMETEXT_23B_DFPT_Kyte_reactions_2 = 0x23B, //Krystal..It looks like you've shut off one of the power beams !
        GAMETEXT_23C_WM_Scales_escapes_with_Kyte = 0x23C, //Start the propellor.
        GAMETEXT_23D_CRF_Screens_1 = 0x23D, //CLOUDRUNNER DUNGEONS
        GAMETEXT_23E_CRF_Screens_2 = 0x23E, //WIND LIFT
        GAMETEXT_23F_CRF_Screens_3 = 0x23F, //POWER ROOM
        GAMETEXT_240_CRF_Screens_4 = 0x240, //CLOUDRUNNER DOCKING PLATFORM
        GAMETEXT_241_CRF_Screens_5 = 0x241, //THE ROYAL CHAMBER
        GAMETEXT_242_CRF_Screens_6 = 0x242, //TREASURE ROOMS
        GAMETEXT_243_CRF_Screens_7 = 0x243, //THE JEWEL MINES
        GAMETEXT_244_CRF_Screens_8 = 0x244, //GUNPOWER STORAGE
        GAMETEXT_245_DF_Meeting_the_HighTop = 0x245, //So you must be Krystal,
        GAMETEXT_246_GP_SharpClaw_steal_SpellStone = 0x246, //What's he doing up there?
        GAMETEXT_247_Tutorial_Combat = 0x247, //This is a SHARPCLAW. Tap or Hold the Z BUTTON to lock the camera onto him.
        GAMETEXT_248_Tutorial_Magic_Gem = 0x248, //You have picked up a ...MAGIC GEM!!
        GAMETEXT_249_Tutorial_Energy_Eggs = 0x249, //These are ...ENERGY EGGS
        GAMETEXT_24A_Tutorial_Dino_Fruits = 0x24A, //These are ...DINO FRUITS They are found growing in the trees.
        GAMETEXT_24B_Tutorial_Small_Scarab_Bag = 0x24B, //You have collected a ...SHARPCLAW SCARAB BAG! Scarabs are Dinosaur Planet's currency.
        GAMETEXT_24C_Tutorial_Scarab = 0x24C, //This is a ...SCARAB!! They are the currency of Dinosaur Planet!
        GAMETEXT_24D_Tutorial_Projectile_Spell = 0x24D, //You have collected your first Magic Spell! The PROJECTILE SPELL!!
        GAMETEXT_24E_Tutorial_Energy_Holder = 0x24E, //You have earned your first ...ENERGY HOLDER!
        GAMETEXT_24F_Tutorial_Warp_Crystal = 0x24F, //You have collected your first Object, a WARP CRYSTAL!
        GAMETEXT_250_Tutorial_Duster = 0x250, //This is a ...DUSTER!
        GAMETEXT_251_Tutorial_Magic_Holder = 0x251, //This is a ...MAGIC HOLDER!
        GAMETEXT_252_Tutorial_Z_Lock_Icon_Objects = 0x252, //When the Z LOCK Icon appears on or above an object, it means it can be interacted with.
        GAMETEXT_253_Tutorial_Pushing_Pulling = 0x253, //This block can be ...PUSHED or PULLED!
        GAMETEXT_254_Tutorial_Jet_Bike = 0x254, //To power the Jet Bike push forwards on the CONTROL STICK to go faster. Pull back to slow down.
        GAMETEXT_255_Tutorial_Magic_Crystal_Plant = 0x255, //This is a MAGIC CRYSTAL PLANT!!
        GAMETEXT_256_Tutorial_Z_Lock_Icon_Conversation = 0x256, //When the Z LOCK Icon appears on or above a dinosaur, it means you can interact with it.
        GAMETEXT_257_Tutorial_Sidekick_Food = 0x257, //This is a ...BLUE MUSHROOM!! They are dinosaurs favourite food!
        GAMETEXT_258_Tutorial_Krazoa_Spirits = 0x258, //You have placed the first ...KRAZOA SPIRIT!
        GAMETEXT_259_Empty = 0x259,
        GAMETEXT_25A_Empty = 0x25A,
        GAMETEXT_25B_Empty = 0x25B,
        GAMETEXT_25C_Empty = 0x25C,
        GAMETEXT_25D_Empty = 0x25D,
        GAMETEXT_25E_WM_Randorn_and_Krystal_Meeting_1 = 0x25E, //Randorn Whats happened to you!
        GAMETEXT_25F_Empty = 0x25F,
        GAMETEXT_260_WM_Randorn_and_Krystal_Meeting_2 = 0x260, //They must be scattered all over the planet by now.
        GAMETEXT_261_WM_Randorn_and_Krystal_Meeting_3 = 0x261  //But theres something else,
} GameTexts;

#endif // _GAME_GAMETEXTS_H
