#ifndef _SYS_GAME_INVENTORY_ITEMS_H
#define _SYS_GAME_INVENTORY_ITEMS_H

typedef enum {
    INVENTORY_ITEM_KRYSTAL_0_WM_WARP_CRYSTAL = 0,
    INVENTORY_ITEM_KRYSTAL_1_CRF_PRISON_KEY_CRF = 1,
    INVENTORY_ITEM_KRYSTAL_2_CRF_POWER_ROOM_KEY = 2,
    INVENTORY_ITEM_KRYSTAL_3_CRF_RED_POWER_CRYSTAL = 3,
    INVENTORY_ITEM_KRYSTAL_4_CRF_GREEN_POWER_CRYSTAL = 4,
    INVENTORY_ITEM_KRYSTAL_5_CRF_BLUE_POWER_CRYSTAL = 5,
    INVENTORY_ITEM_KRYSTAL_6_CRF_SNOWBIKE_KEY = 6, //unused
    INVENTORY_ITEM_KRYSTAL_7_MINE_KEY = 7, //unused
    INVENTORY_ITEM_KRYSTAL_8_ALPINE_ROOT = 8, //unused
    INVENTORY_ITEM_KRYSTAL_9_DIM_GEAR_1 = 9, //unused
    INVENTORY_ITEM_KRYSTAL_10_DIM_GEAR_2 = 10, //unused
    INVENTORY_ITEM_KRYSTAL_11_DIM_GEAR_3 = 11, //unused
    INVENTORY_ITEM_KRYSTAL_12_DIM_GEAR_4 = 12, //unused
    INVENTORY_ITEM_KRYSTAL_13_FOOD_BAG_SMALL = 13,
    INVENTORY_ITEM_KRYSTAL_14_FOOD_BAG_MEDIUM = 14,
    INVENTORY_ITEM_KRYSTAL_15_FOOD_BAG_LARGE = 15,
    INVENTORY_ITEM_KRYSTAL_16_GRUB_BAG_SMALL = 16,
    INVENTORY_ITEM_KRYSTAL_17_GRUB_BAG_MEDIUM = 17,
    INVENTORY_ITEM_KRYSTAL_18_GRUB_BAG_LARGE = 18,
    INVENTORY_ITEM_KRYSTAL_19_GOLD_NUGGET_1_GP = 19,
    INVENTORY_ITEM_KRYSTAL_20_GOLD_NUGGET_2_LFV = 20,
    INVENTORY_ITEM_KRYSTAL_21_FIRE_CRYSTAL = 21,
    INVENTORY_ITEM_KRYSTAL_22_CC_CELL_DOOR_KEY = 22,
    INVENTORY_ITEM_KRYSTAL_23_SPELLSTONE_CRF_ACTIVATED = 23,
    INVENTORY_ITEM_KRYSTAL_24_SPELLSTONE_BWC_ACTIVATED = 24,
    INVENTORY_ITEM_KRYSTAL_25_SPELLSTONE_KP_ACTIVATED = 25,
    INVENTORY_ITEM_KRYSTAL_26_KRAZOA_TRANSLATOR = 26,
    INVENTORY_ITEM_KRYSTAL_27_HORN_OF_TRUTH = 27,
    INVENTORY_ITEM_KRYSTAL_28_CRF_TREASURE_CHEST_KEY = 28,
    INVENTORY_ITEM_KRYSTAL_29_BLUE_MUSHROOM = 29, //grubs
    INVENTORY_ITEM_KRYSTAL_30_FIREFLY_LANTERN = 30,
    INVENTORY_ITEM_KRYSTAL_31_PRISON_KEY_CRF = 31,
    INVENTORY_ITEM_KRYSTAL_32_KRAZOA_TABLET = 32,
    INVENTORY_ITEM_KRYSTAL_33_MOONSEEDS = 33,
    INVENTORY_ITEM_KRYSTAL_34_CRF_CONSTRUCTION_ENGINEERS_KEY = 34,
    INVENTORY_ITEM_KRYSTAL_35_GOLD_NUGGET_3_CC = 35
} InventoryItemIndicesKrystal;

typedef enum {
    INVENTORY_ITEM_SABRE_0_NW_GATE_KEY = 0, //unused
    INVENTORY_ITEM_SABRE_1_SW_ALPINE_ROOT = 1,
    INVENTORY_ITEM_SABRE_2_BLUE_MUSHROOM = 2,
    INVENTORY_ITEM_SABRE_3_PURPLE_MUSHROOM = 3,
    INVENTORY_ITEM_SABRE_4_WHITE_MUSHROOM = 4,
    INVENTORY_ITEM_SABRE_5_MINE_KEY = 5,
    INVENTORY_ITEM_SABRE_6_DIM_ALPINE_ROOT = 6,
    INVENTORY_ITEM_SABRE_7_DIM_GEAR_1 = 7,
    INVENTORY_ITEM_SABRE_8_DIM_GEAR_2 = 8,
    INVENTORY_ITEM_SABRE_9_DIM_GEAR_3 = 9,
    INVENTORY_ITEM_SABRE_10_DIM_GEAR_4 = 10,
    INVENTORY_ITEM_SABRE_11_DIM_BELINA_TE_CELL_KEY = 11,
    INVENTORY_ITEM_SABRE_12_DIM_TRICKY_CELL_KEY = 12,
    INVENTORY_ITEM_SABRE_13_WM_WARP_CRYSTAL = 13,
    INVENTORY_ITEM_SABRE_14_DIM_DOOR_KEY_1 = 14,
    INVENTORY_ITEM_SABRE_15_DIM_DOOR_KEY_2 = 15,
    INVENTORY_ITEM_SABRE_16_FOOD_BAG_SMALL = 16,
    INVENTORY_ITEM_SABRE_17_FOOD_BAG_MEDIUM = 17,
    INVENTORY_ITEM_SABRE_18_FOOD_BAG_LARGE = 18,
    INVENTORY_ITEM_SABRE_19_MUSHROOM_BAG_SMALL = 19,
    INVENTORY_ITEM_SABRE_20_MUSHROOM_BAG_MEDIUM = 20,
    INVENTORY_ITEM_SABRE_21_MUSHROOM_BAG_LARGE = 21,
    INVENTORY_ITEM_SABRE_22_CORRUPT_FORCEFIELD_SPELL = 22, //unused, possibly for WMConsoleStone?
    INVENTORY_ITEM_SABRE_23_HORN_OF_TRUTH = 23,
    INVENTORY_ITEM_SABRE_24_FIREFLY_LANTERN = 24,
    INVENTORY_ITEM_SABRE_25_WC_SILVER_TOOTH = 25,
    INVENTORY_ITEM_SABRE_26_WC_GOLD_TOOTH = 26,
    INVENTORY_ITEM_SABRE_27_WC_SUN_STONE = 27,
    INVENTORY_ITEM_SABRE_28_WC_MOON_STONE = 28,
    INVENTORY_ITEM_SABRE_29_MOONSEEDS = 29,
    INVENTORY_ITEM_SABRE_30_SPELLSTONE_DIM_INACTIVE = 20,
    INVENTORY_ITEM_SABRE_31_SPELLSTONE_DIM_ACTIVATED = 31,
    INVENTORY_ITEM_SABRE_32_SPELLSTONE_WC_ACTIVATED = 32,
    INVENTORY_ITEM_SABRE_33_SPELLSTONE_DR_ACTIVATED = 33,
    INVENTORY_ITEM_SABRE_34_DB_POINTBACK_EGG = 34,
    INVENTORY_ITEM_SABRE_35_DB_BAY_DIAMOND = 35
} InventoryItemIndicesSabre;

typedef enum {
    INVENTORY_SPELL_0_PROJECTILE = 0,
    INVENTORY_SPELL_1_ICE_BLAST = 1,
    INVENTORY_SPELL_2_GRENADE = 2,
    INVENTORY_SPELL_3_ILLUSION = 3,
    INVENTORY_SPELL_4_FORCEFIELD = 4,
    INVENTORY_SPELL_5_GLITCHED = 5,
    INVENTORY_SPELL_6_GLITCHED = 6,
    INVENTORY_SPELL_7_PORTAL = 7,
    INVENTORY_SPELL_8_MIND_READ = 8
}  InventorySpellIndices;

typedef enum {
    ICON_WARP_CRYSTAL = 0x0245,
    ICON_KEY = 0x0175,
    ICON_MOON_MOUNTAIN_PASS_KEY = 0x0568, //unused?
    ICON_POWER_ROOM_KEY = 0x0176,
    ICON_RED_POWER_CRYSTAL = 0x0180,
    ICON_GREEN_POWER_CRYSTAL = 0x0181,
    ICON_BLUE_POWER_CRYSTAL = 0x0182,
    ICON_ALPINE_ROOT = 0x01a3,
    ICON_DIM_COG = 0x0479,
    ICON_SMALL_FOOD_BAG = 0x027a,
    ICON_MEDIUM_FOOD_BAG = 0x0244,
    ICON_LARGE_FOOD_BAG = 0x02bf,
    ICON_SMALL_DINO_BAG = 0x0471,
    ICON_UPGRADED_DINO_BAG = 0x0560,
    ICON_GOLD_NUGGET = 0x0257,
    ICON_FIRE_CRYSTAL = 0x04f7,
    ICON_KRAZOA_ARTIFACT = 0x0496,      //shared by the Translator & Tablets
    ICON_HORN_OF_TRUTH = 0x0258,
    ICON_TREASURE_CHEST_KEY = 0x0568,
    ICON_BLUE_MUSHROOM = 0x01a5,
    ICON_FIREFLY_LANTERN = 0x046d,
    ICON_MOONSEEDS = 0x040d,
    ICON_PURPLE_MUSHROOM = 0x0498,
    ICON_WHITE_MUSHROOM = 0x0497,
    ICON_SILVER_TOOTH = 0x052b,
    ICON_TREX_TOOTH = 0x025b,           //unused?
    ICON_GOLD_TOOTH = 0x052a,
    ICON_SUN_STONE = 0x03a8,
    ICON_MOON_STONE = 0x03d6,
    ICON_POINTBACK_EGG = 0x055e,
    ICON_BAY_DIAMOND = 0x055f,
    ICON_SPELLSTONE_INACTIVE = 0x0562,
    ICON_SPELLSTONE_ACTIVE = 0x0563,
    ICON_SCARAB = 0x0475,               //unused

    ICON_EAT_FOOD = 0x02c7,
    ICON_PLACE_FOOD = 0x02c8,
    ICON_GIVE_FOOD = 0x02ef,
    ICON_TAKE_FOOD = 0x0265,
    ICON_DINO_EYE = 0x0529,
    
    ICON_GREEN_APPLE = 0x026e,
    ICON_RED_APPLE = 0x026f,
    ICON_BROWN_APPLE = 0x0270,
    ICON_FISH = 0x0272,
    ICON_SMOKED_FISH = 0x02c6,
    ICON_MEAT = 0x02c4,
    ICON_MOLDY_MEAT = 0x02c5,
    
    ICON_MAGIC_SPELL = 0x03A9, //unused
    ICON_PROJECTILE_SPELL = 0x0183,
    ICON_ICE_BLAST_SPELL = 0x0468,
    ICON_GRENADE_SPELL = 0x04f8,
    ICON_ILLUSION_SPELL = 0x0177,
    ICON_FORCEFIELD_SPELL = 0x0265,
    ICON_PORTAL_SPELL = 0x0466,
    ICON_MIND_READ_SPELL = 0x0470,
    
    ICON_HEEL = 0x01cd,
    ICON_PLAY = 0x01d1,
    ICON_FIND = 0x01ce,
    ICON_FLAME = 0x01cf,
    ICON_DISTRACT = 0x01d0,
    ICON_GUARD = 0x01d2
} InventoryIcons;

#endif
