/** OS threads
 */
#ifndef _SYS_THREAD_H
#define _SYS_THREAD_H

#define IDLE_THREAD_SIZE 0x40
#define IDLE_THREAD_ID 1
#define IDLE_THREAD_PRIORITY OS_PRIORITY_IDLE

#define MAIN_THREAD_SIZE 0x2000
#define MAIN_THREAD_ID 3
#define MAIN_THREAD_PRIORITY 10

#define OS_SCHEDULER_THREAD_ID 5
#define OS_SCHEDULER_THREAD_PRIORITY 13

#define CONTROLLER_THREAD_ID 98
#define CONTROLLER_THREAD_PRIORITY 12

#define RESET_THREAD_ID 100
#define RESET_THREAD_PRIORITY 0x80

#define ASSET_THREAD_ID 99
#define ASSET_THREAD_PRIORITY 11

#define AUDIO_THREAD_ID 4
#define AUDIO_THREAD_PRIORITY 14

#define DI_CPU_THREAD_ID (-1)
#define DI_CPU_THREAD_PRIORITY OS_PRIORITY_MAX

#endif //_SYS_THREAD_H
